<Project Sdk="Microsoft.NET.Sdk">
  
  <ItemGroup>
    <ProjectReference Include="..\TaxMate.Model\TaxMate.Model.csproj" />
    <ProjectReference Include="..\TaxMate.Service\TaxMate.Service.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="CloudinaryDotNet" Version="1.29.2" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1" />
    <PackageReference Include="Google.Apis.Auth" Version="1.73.0" />
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.6.1" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />

    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.8" />

    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.8" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.3.0" />
    <PackageReference Include="QuestPDF" Version="2024.12.1" />
    <PackageReference Include="Twilio" Version="7.14.9" />
  </ItemGroup>
  
  <ItemGroup>
    <Folder Include="Templates\Tax\2026\" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Templates\Tax\2026\mau-01-cnkd.docx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Word\mau-s2a-HKD.docx" CopyToOutputDirectory="PreserveNewest" Link="Word\mau-s2a-HKD.docx" />
  </ItemGroup>

</Project>
